---Generated with github.com/volskaya/irrelevant.
local {{name}} = {
  none = "NONE",

  borderDark = "{{borderDark}}",
  borderLight = "{{borderLight}}",

  background = "{{backgroundTerminal}}",
  backgroundTerminal = "{{backgroundTerminal}}",
  foreground = "{{foreground}}",
  foregroundActive = "{{gray4}}",
  foregroundInactive = "{{comment}}",

  surface = "{{surface}}",
  modal = "{{modal}}",
  modalFocus = "{{modalFocus}}",
  comment = "{{comment}}",
  divider = "{{divider}}",
  highlight = "{{highlight}}",
  illuminate = "{{gray0}}", -- Has to be visible above modal.
  lineHighlight = "{{lineHighlight}}",
  indentGuide = "{{indentGuide}}",
  indent = "{{indentGuide}}",
  irrelevant = "{{comment}}",
  underline = "{{accent}}",
  todo = "{{foreground}}",

  accent = "{{accent}}",
  onAccent = "{{onAccent}}",
  number = "{{number}}",
  string = "{{strings}}",
  bracket = "{{bracket}}",
  operator = "{{comment}}",
  danger = "{{danger}}",
  warning = "{{warning}}",
  success = "{{success}}",
  onDanger = "{{onAccent}}",

  base04 =  "{{gray04}}",
  base03 = "{{gray03}}",
  base02 = "{{gray02}}",
  base01 = "{{gray01}}",
  base00 = "{{gray00}}",
  base0 = "{{gray0}}",
  base1 = "{{gray1}}",
  base2 = "{{gray2}}",
  base3 = "{{gray3}}",
  base4 = "{{gray4}}",

  gray0 = "{{gray0}}",
  gray1 = "{{gray1}}",
  gray2 = "{{gray2}}",
  gray3 = "{{gray3}}",
  gray4 = "{{gray4}}",
  gray5 = "{{gray5}}",
  gray6 = "{{gray6}}",
  gray00 = "{{gray00}}",
  gray01 = "{{gray01}}",
  gray02 = "{{gray02}}",
  gray03 = "{{gray03}}",
  gray04 = "{{gray04}}",
  gray05 = "{{gray05}}",
  gray06 = "{{gray06}}",

  -- Somewhat backwards compatability with rainbow colors, in case anyone needs.
  yellow = "{{accent}}",
  orange = "{{comment}}",
  red = "{{comment}}",
  magenta = "{{comment}}",
  violet = "{{comment}}",
  blue = "{{accent}}",
  cyan = "{{comment}}",
  green = "{{accent}}",

  -- LSP colors.
  stringColor = "{{stringColor}}",
  booleanColor = "{{booleanColor}}",
  objectColor = "{{objectColor}}",
  irrelevantObjectColor = "{{irrelevantObjectColor}}",
  numberColor = "{{numberColor}}",
  variableColor = "{{variableColor}}",
  argumentColor = "{{argumentColor}}",
  operatorColor = "{{operatorColor}}",
  methodColor = "{{methodColor}}",
  languageConstantColor = "{{languageConstantColor}}",
}

return {{name}}
